### ISSUE TITLE
Treat Excalidraw files as attachments

### ISSUE THREAD

**Issue by ms3056** [husjon/obsidian-file-cleaner-redux#68] opened 2024-09-05 00:25 UTC
I have a lot of empty Excalidraw drawings embedded in my notes. I do this in case I want to draw a picture in a note, so every meeting note contains an empty Excalidraw drawing. 

When I ran this plugin today, ANY file - even if it has other content like text or images - was flagged for deletion because they contain empty Excalidraw files. 

REQUEST: please allow a setting to TURN THIS OFF!!!!

Here is an example - all of these were flagged for deletion - but - they all have content (and have empty Excalidraw content). 

![SP-01-2024-09-05 09h19_16](https://github.com/user-attachments/assets/c2be30d5-0556-4646-bd70-0713c82e5b25)

**Comment by husjon** [comment] 2024-09-05 08:46
Having a lot of empty drawings feels counter-intuitive to me, however I can also see why one would need it.
I'll add an option to the settings to toggle it later today.

**Comment by husjon** [comment] 2024-09-05 15:03
Just a heads up that I've pushed a patch to disable cleanup of Excalidraw file for now (v1.1.1).

**Comment by ms3056** [comment] 2024-09-06 02:52
I have attached a typical note. This has embedded Excalidraw drawings that are 'blank' to start. In case someone is like "why?" - I have a hotkey to "swap" between the Obsidian text entry view and the Excalidraw "drawing" view - its kinda like Obsidian is one side of the "paper" where I type notes, and Excalidraw is the back side of the paper where you can draw images. Then hot-key back and forth at will. 

I hope this helps. This attached files is one of the files and the content that the previous version tried to delete. 


[20240906101539.md](https://github.com/user-attachments/files/16902233/20240906101539.md)

**Comment by husjon** [comment] 2024-09-06 09:01
Aha that is actually a really nice way of using it :)

I will spend some more time looking into the implementation for cleaning up Excalidraw files.
It will take a bit longer to implement but the end result will be so that Excalidraw files are handled more like pictures etc in that if they are ignored if in use by any other file.

**Comment by husjon** [comment] 2024-09-08 13:13
Hi, I've now made a pre-release version with a fixed version of the original implementation ([v1.1.2-0](https://github.com/husjon/obsidian-file-cleaner-redux/releases/tag/1.1.2-0)).

It now does a pre-check to see if it has any backlinks / references (this was the part that was missing from the original implementation) and if so, skips the cleanup for that particular Excalidraw file.

On my end it seem to work as intended, but I would like for you to give it a shot to if possible, either in a test vault or your main.
The pre-release can be tested by using the [BRAT plugin](https://obsidian.md/plugins?id=obsidian42-brat).

Once BRAT has been installed and enabled, go to the settings tab for the plugin and click `Add Beta plugin with frozen version`, then fill in the following:  
Repository: `https://github.com/husjon/obsidian-file-cleaner-redux`  
Release Version: `1.1.2-0` (notice the lack of `v` prefix)

You'll see it in BRAT shortly after adding it, like this.
![image](https://github.com/user-attachments/assets/acee105b-c03c-46ff-b375-c413f7137a9f)

You can confim the version in the community plugin tab
![image](https://github.com/user-attachments/assets/3c89f69c-f678-4823-9206-7a75a98cadcb)

Once installed, see if it works as you expect.
If it works as expected I will make it public otherwise I'll make a few adjustments according you what you find. :)

**Finally**: To remove the beta version, disable / uninstall BRAT, then re-install File Cleaner Redux through the community plugin listing.

Thanks in advance

**Comment by husjon** [comment] 2024-09-10 19:32
I found a bug which cause a rather big slowdown since it was trying to parse markdown files twice, this has now been pushed to 1.1.2-1, the procedure above is still correct except for the version to test is now `1.1.2-1`

**Comment by husjon** [comment] 2024-11-13 21:02
@ms3056 and @Iphinis, were you able to test according to my previous message https://github.com/husjon/obsidian-file-cleaner-redux/issues/68#issuecomment-2336682289?
And if so did it work how you wanted?

**Comment by Iphinis** [comment] 2024-11-15 12:03
Hello, sorry for the delay,

I just tested your plugin, when I exclude ".md" it doesn't work, the plugin still wants to delete empty markdown files.

Also I tought that it cleaned unattached Excalidraw files but it doesn't (I disabled the Excalidraw JSON compression).

**Comment by husjon** [comment] 2024-11-16 11:05
No worries, I was going through the issues just to see if there were any to be picked up on / closed.
I haven't look into this one since back in September so there might definitely be some issues.

Regarding disabling the JSON compression in Excalidraw, is that with newly created files after disabling it or is it with existing files?
If I remember correctly just disabling it isn't enough, you'd have to go into each Excalidraw file and save it manually at least once (this is so that Excalidraw can save it without compression).

**Comment by Iphinis** [comment] 2024-11-16 13:54
I'm testing in a sandbox vault, and it doesn't ask me to delete drawings in both cases, even if I save them.
By the way, the plugin is up to date.

**Comment by husjon** [comment] 2024-11-16 15:24
Thanks for the update.

> By the way, the plugin is up to date.

Just to make sure, this is using version 1.1.2-1 (as described in https://github.com/husjon/obsidian-file-cleaner-redux/issues/68#issuecomment-2336682289)? :)

**Comment by Iphinis** [comment] 2024-11-16 16:10
Unfortunately, I have the same problems, empty notes are not ignored even if I only include .png, .excalidraw.md, .excalidraw, and not if I exclude them with .md

Excalidraw files are now detected but they have the same problem as .md empty notes.

It seems that these files are detected even if I don't include (or exclude) them.

However, it seems to work well with other extensions such as .png, but I think it was already the case in previous versions.

**Comment by husjon** [comment] 2024-11-16 21:00
Empty normal markdown files (`.md`) will always be targeted for cleanup, that's the default behaviour.
The only exception to this is if another file is referencing / linking to it.

Example screenshot (**A** links to **B** while **B** is empty, **B** will not be removed):
![image](https://github.com/user-attachments/assets/b4fed1bd-22c0-401c-b2ce-2def7ee2dd11)




> Excalidraw files are now detected but they have the same problem as .md empty notes.

This should follow the same rule as above.

If you create a new note and and the only content is a link to an Excalidraw file, is the Excalidraw file still being removed?

**Comment by Iphinis** [comment] 2024-11-25 22:26
Hello, 
> If you create a new note and and the only content is a link to an empty Excalidraw file, is the Excalidraw file still being removed?
If that is the case, I will need to take a closer look at it :)

I just tested that and it is the case

**Comment by husjon** [comment] 2024-11-26 10:51
Thanks @Iphinis I'll take a look at this over the next few days and get back to you.

**Comment by Iphinis** [comment] 2024-12-13 22:36
Hi, 

I just configured the following sandbox vault thanks to your instructions :
![image](https://github.com/user-attachments/assets/bc343db1-7184-45cc-9c6c-4ea0dc2aea62)

and tested this :
> If you create a new note and and the only content is a link to an empty Excalidraw file, is the Excalidraw file still being removed?
If that is the case, I will need to take a closer look at it :)

Now it doesn't clean the drawing anymore (I tested both situations with/out saving the empty drawing), which is the intended purpose, thank you very much!

![image](https://github.com/user-attachments/assets/2d74a9a2-c444-478f-8cd7-7ff2850fc9d2)

**Comment by husjon** [comment] 2024-12-14 09:36
Thank for testing it @Iphinis.
I'll go ahead and merge the changes, they will be part of version 1.3.0.

This issue will be closed automatically when they're merged.

**Closed** 2024-12-14 09:57 UTC
Labels: bug
